# URL of your Matrix Homeserver Instance
homeserver: https://example.org
# Homeserver domain (domain part of the mxid)
domain: example.org
# Application Service Token from the matrix Homeserver
as_token: very-secret
# Don't download files from Slack and upload them to Matrix
skip-files: False
# Slack token?
slack_token: someslacktoken
# Path to the Slack Backup relative to the current directory or absolute
zipfile: ./Slack_Export.zip
# Set to 'True' to perform a test without making changes to the homeserver
dry-run: False
# Set to 'False' if archived Channels from Slack should be migrated (and accessible in Matrix)
skip-archived: True
