# URL of your Matrix Homeserver Instance
homeserver: https://example.org
# Homeserver domain (domain part of the mxid)
domain: example.org
# Application Service Token from the matrix Homeserver
as_token: very-secret
# Verify https certificate (True) or ignore 'unsafe' SSL certificates (False)
verify-ssl: True
# Don't download files from Slack and upload them to Matrix
skip-files: False
# Path to the Slack Backup relative to the current directory or absolute
zipfile: /data/Slack_Export.zip
# Set to 'True' to perform a test without making changes to the homeserver
dry-run: False
# Set to 'True' to run without asking for confirmation after each step
run-unattended: False
# Set to 'False' if archived Channels from Slack should be migrated (and accessible in Matrix)
skip-archived: True
# Set to 'True' to invite all users to all rooms ( Very slow on rooms creator whit many users )
invite-all: False
# Set to 'True' to invite user if get 403 on migrate message need create-as-admin=True
invite-if-403: true
# Set to 'True' to invite the admin user to all rooms
create-as-admin: False
# Set to 'True' to kick all imported users from imported rooms
kick-imported-users: False
# Import public channels as private rooms
import-as-private: False
# Set to 'True' to allow rooms to be joined from other homeservers
federate-rooms: False
# Reply thread messages to previous thread message instead of parent message
threads-reply-to-previous: True
# Append room and displayname suffixes
room-suffix: ""
name-suffix: ""
